In [1]:
import numpy as np

In [2]:
path = "C:\\Users\\adeel\\Documents\\Teaching\\ML\\Notebooks\\regression_dataset\\" 
trnData = np.loadtxt(path+"train.csv", delimiter = ",", skiprows = 1)
tstData = np.loadtxt(path+"test.csv", delimiter = ",", skiprows = 1)

In [3]:
print(np.shape(trnData))
print(np.shape(tstData))

(699, 2)
(300, 2)


In [4]:
trn_X = trnData[:,0]
trn_y = trnData[:,1]
tst_X = tstData[:,0]
tst_y = tstData[:,1]


In [5]:
print(np.shape(trn_X))
print(np.shape(trn_y))
print(np.shape(tst_X))
print(np.shape(tst_y))

(699,)
(699,)
(300,)
(300,)


In [6]:
A = np.zeros((2,2))
X = np.zeros((2))
B = np.zeros((2))

In [7]:
A[0,0] = float(np.shape(trn_X)[0])
A[0,1] = float(np.sum(trn_X))
A[1,0] = float(np.sum(trn_X))
A[1,1] = float(np.sum(trn_X**2))

In [8]:
print(A)

[[6.99000e+02 3.49600e+04]
 [3.49600e+04 2.33368e+06]]


In [9]:
B[0] = float(np.sum(trn_y))
B[1] = float(np.sum(trn_X * trn_y))

In [10]:
print(B)

[  34907.96855015 2331461.78457846]


In [11]:
A_inv = np.linalg.inv(A)

In [12]:
print(A_inv)

[[ 5.70525106e-03 -8.54682634e-05]
 [-8.54682634e-05  1.70887632e-06]]


In [13]:
X = np.dot(A_inv, B)

In [14]:
print(X)

[-0.10726546  1.00065638]


In [15]:
tst_y_pred = X[0]+X[1]*tst_X
trn_y_pred = X[0]+X[1]*trn_X

In [16]:
print(tst_y_pred[:5])
print(tst_y[:5])

[76.94327594 20.90651855 21.90717494 19.90586217 35.91636428]
[79.77515201 23.17727887 25.60926156 17.85738813 41.84986439]


In [17]:
print(trn_y_pred[:5])
print(trn_y[:5])

[23.9084877  49.92555363 14.90258026 37.91767705 86.94983976]
[21.54945196 47.46446305 17.21865634 36.58639803 87.28898389]
